// from https://github.com/jamesseanwright/ron-swanson-quotes/blob/master/quotes.js
// and from http://www.imdb.com/character/ch0144619/quotes

module.exports = [
    "Clear alcohols are for rich women on diets.",
    "Crying: acceptable at funerals and the Grand Canyon.",
    "I call this turf ‘n’ turf. It's a 16 oz T-bone and a 24 oz porterhouse. Also, whiskey and a cigar. I am going to consume all of this at the same time because I am a free American.",
    "Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons.",
    "I'm a simple man. I like pretty, dark-haired women, and breakfast food.",
    "Never half-ass two things. Whole-ass one thing.",
    "[On bowling] Straight down the middle. No hook, no spin, no fuss. Anything more and this becomes figure skating.",
    "I don't want to paint with a broad brush here, but every single contractor in the world is a miserable, incompetent thief.",
    "Fishing relaxes me. It's like yoga, except I still get to kill something.",
    "No home is complete without a proper toolbox. Here's April and Andy's: A hammer, a half eaten pretzel, a baseball card, some cartridge that says Sonic and Hedgehog, a scissor half, a flashlight filled with jellybeans.",
    "Just give me all the bacon and eggs you have. Wait...wait. I worry what you just heard was: Give me a lot of bacon and eggs. What I said was: Give me all the bacon and eggs you have. Do you understand?",
    "When people get a little too chummy with me I like to call them by the wrong name to let them know I don't really care about them.",
    "There's only one thing I hate more than lying: skim milk. Which is water that's lying about being milk.",
    "The government is a greedy piglet that suckles on a taxpayer's teat until they have sore, chapped nipples.",
    "The less I know about other people's affairs, the happier I am. I'm not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.",
    "When I eat, it is the food that is scared.",
    "My only official recommendations are US Army-issued mustache trimmers, Morton's Salt, and the C.R. Lawrence Fein two inch axe-style scraper oscillating knife blade.",
    "Are you going to tell a man that he can't fart in his own car?",
    "Turkey can never beat cow.",
    "It's always a good idea to demonstrate to your coworkers that you are capable of withstanding a tremendous amount of pain.",
    "There are three acceptable haircuts: high and tight, crew cut, buzz cut.",
    "Capitalism: God's way of determining who is smart and who is poor.",
    "Any dog under fifty pounds is a cat and cats are useless.",
    "Fish, for sport only, not for meat. Fish meat is practically a vegetable.",
    "There is only one bad word: taxes.",
    "History began July 4th, 1776. Anything before that was a mistake.",
    "Cultivating a manly musk puts your opponents on notice.",
    "Give a man a fish and feed him for a day. Don't teach a man to fish… and feed yourself. He's a grown man. And fishing's not that hard.",
    "Child labor laws are ruining this country.",
    "Great job, everyone. The reception will be held in each of our individual houses, alone.",
    "America: The only country that matters. If you want to experience other cultures, use an atlas or a ham radio.",
    "The key to burning an ex-wife effigy is to dip it in paraffin wax and then toss the flaming bottle of isopropyl alcohol from a safe distance. Do not stand too close when you light an ex-wife effigy.",
    "There are only three ways to motivate people: money, fear, and hunger.",
    "Shorts over six inches are capri pants, shorts under six inches are European.",
    "Friends: one to three is sufficient.",
    "Breakfast food can serve many purposes.",
    "Honor: if you need it defined, you don't have it.",
    "One rage every three months is permitted. Try not to hurt anyone who doesn't deserve it.",
    "Strippers do nothing for me... but I will take a free breakfast buffet anytime, anyplace.",
    "I like saying \"No\", it lowers their enthusiasm.",
    "You had me at meat tornado.",
    "There must be a mistake, you've accidentally given me the food that my food eats.",
    "Son, there is no wrong way to consume alcohol.",
    "Keep your tears in your eyes where they belong.",
    "I've cried twice in my life. Once when I was seven and hit by a school bus. And then again when I heard that Li'l Sebastian has passed.",
    "I hate everything.",
    "I love nothing.",
    "Don't waste energy moving unless necessary.",
    "I'll take that steak to go. Please and thank you.",
    "Creativity is for people with glasses who like to lie.",
    "Children are terrible artists and artists are crooks.",
    "Tom put all my records into this rectangle!",
    "I believe luck is a concept invented by the weak to explain their failures.",
    "What's cholesterol?",
    "People who buy things are suckers.",
    "I'm going to get 12 eggs and part of a dead animal. Dealer's choice. Please and thank you.",
    "What the f*ck is a German muffin?!?",
    "I wanna punch you in the face so bad right now.",
    "A dog under fifty pounds is a cat and cats are useless.",
    "Dear frozen yogurt, you are the celery of desserts. Be ice cream, or be nothing.",
    "Yeah, I'm just gonna stay angry. I find that relaxes me.",
    "Only sweat during physical activity and love making. No emotional sweating.",
    "I love Food and Stuff. It's where I buy all of my food. And most of my stuff.",
    "My dream is to have the parks system privatized and run entirely for profit, by corporations.",
    "I don't drink alcohol from that portion of the color spectrum.",
    "Birthdays were invented by Hallmark to sell cards.",
    "I have a hernia. I've had it for a while. And I've been ignoring it... successfully, but this morning, I made the mistake of sneezing.",
    "There has never been a sadness that can't be cured by breakfast food.",
    "I can't think of anything more noble to go to war over than bacon and eggs.",
    "Body Grooming: Only women shave below the neck.",
    "Handshakes: Firm, dry, solid, 3 seconds.",
    "Poise: Sting like a bee. Do not float like a butterfly. That’s ridiculous.",
    "Rage: One rage every three months is permitted. Try not to hurt anyone who doesn’t deserve it.",
    "Cursing: There’s only one bad word; Taxes. If any other word is good enough for sailors, it’s good enough for you.",
    "I would sooner visit Europe than have something romantic happen between us.",
    "The whole point of this country is if you want to eat garbage, balloon up to 600 pounds and die of a heart attack at 43, you can! You are free to do so. To me, that’s beautiful.",
    "Capitalism is the only way... It makes America great, England OK, and France terrible.",
    "When I walked in this morning and saw that the flag was half-mast, I thought 'Alright, another bureaucrat ate it!'",
    "My idea of a perfect government is one guy who sits in a small room at a desk and the only thing he’s allowed to decide is who to nuke.",
    "Dammit I love this country so much.",
    "If there was more food and fewer people, this would be a perfect party.",
    "I have the toes I have. Let's just leave it at that.",
    "If it doesn't have meat, it's a snack.",
    "If any of you need anything at all, too bad. Deal with your problems yourselves like adults.",
    "Ann: Do you have any history of mental illness in your family? \nRon: I have an uncle who does yoga."
];